In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
DATABASE = Path.cwd().parent / "app" / "data" / "cleaned" / "data_sales_cleaned.parquet"
pd.set_option('display.max_columns', None)
df = pd.read_parquet(DATABASE)
df

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year,unit_price,profit_margin
0,AG-2011-2040,2011-01-01,2011-06-01,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,OFF-TEN-10000025,Office Supplies,Storage,"Tenex Lockers, Blue",4080000.0,2,0.0,1061400.0,354600.0,Medium,2011,2040000.0,0.26
1,IN-2011-47883,2011-01-01,2011-08-01,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,OFF-SU-10000618,Office Supplies,Supplies,"Acme Trimmer, High Speed",1200000.0,3,0.1,360360.0,97200.0,Medium,2011,400000.0,0.30
2,HU-2011-1220,2011-01-01,2011-05-01,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,OFF-TEN-10001585,Office Supplies,Storage,"Tenex Box, Single Width",660000.0,4,0.0,296400.0,81700.0,High,2011,165000.0,0.45
3,IT-2011-3647632,2011-01-01,2011-05-01,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,OFF-PA-10001492,Office Supplies,Paper,"Enermax Note Cards, Premium",450000.0,3,0.5,-260550.0,48200.0,High,2011,150000.0,-0.58
4,CA-2011-1510,2011-02-01,2011-06-01,Standard Class,Magdelene Morse,Consumer,Ontario,Canada,Canada,Canada,TEC-OKI-10002750,Technology,Machines,"Okidata Inkjet, Wireless",3140000.0,1,0.0,31200.0,241000.0,Medium,2011,3140000.0,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25030,CA-2014-115427,2014-12-12,2015-04-01,Standard Class,Erica Bern,Corporate,California,United States,US,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,210000.0,2,0.2,64750.0,20600.0,Medium,2014,105000.0,0.31
25031,UP-2014-4410,2014-12-12,2015-04-01,Standard Class,Guy Thornton,Consumer,Zaporizhzhya,Ukraine,EMEA,EMEA,OFF-AVE-10003558,Office Supplies,Labels,"Avery Round Labels, Alphabetical",280000.0,4,0.0,61200.0,17000.0,Medium,2014,70000.0,0.22
25032,MX-2014-108574,2014-12-12,2015-04-01,Standard Class,Julia Barnett,Home Office,Tamaulipas,Mexico,LATAM,North,OFF-LA-10004969,Office Supplies,Labels,"Novimex Legal Exhibit Labels, Adjustable",170000.0,3,0.0,6600.0,13200.0,Medium,2014,56700.0,0.04
25033,MO-2014-2560,2014-12-12,2015-05-01,Standard Class,Liz Preis,Consumer,Souss-Massa-Draâ,Morocco,Africa,Africa,OFF-WIL-10001069,Office Supplies,Binders,"Wilson Jones Hole Reinforcements, Clear",40000.0,1,0.0,4200.0,4900.0,Medium,2014,40000.0,0.10
25034,CA-2014-156720,2014-12-12,2015-04-01,Standard Class,Jill Matthias,Consumer,Colorado,United States,US,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,30000.0,3,0.2,-6048.0,1700.0,Medium,2014,10000.0,-0.20

In [17]:
df['customer_name'].value_counts()

customer_name
Frank Olsen         46
Laura Armstrong     45
Bart Watters        45
Kristen Hastings    44
Eric Murdock        44
                    ..
Gary Mitchum        20
Nicole Brennan      17
Sarah Bern          17
Michael Oakman      15
Darren Budd         14
Name: count, Length: 795, dtype: int64

## Create feature for new column as monthly_orders

In [8]:
# Feature engineering to extract the month from the order_date column
df['month'] = df['order_date'].dt.to_period('M')

# Assume df_monthly_sales equal to monthly order
df_monthly_sales = df.groupby('month').agg({'sales': 'count', 'customer_name': 'nunique'}).reset_index()
df_monthly_sales

      month  sales  customer_name
0   2011-01    161            151
1   2011-02    149            135
2   2011-03    166            154
3   2011-04    129            116
4   2011-05    120            113
5   2011-06    142            127
6   2011-07    165            150
7   2011-08    168            152
8   2011-09    145            130
9   2011-10    134            122
10  2011-11    129            119
11  2011-12   2832            777
12  2012-01    152            136
13  2012-02    171            151
14  2012-03    191            160
15  2012-04    156            135
16  2012-05    193            168
17  2012-06    194            167
18  2012-07    186            165
19  2012-08    153            137
20  2012-09    171            156
21  2012-10    196            174
22  2012-11    156            145
23  2012-12   3424            781
24  2013-01    198            174
25  2013-02    222            196
26  2013-03    198            172
27  2013-04    239            195
28  2013-05    237            206
29  2013-06    246            206
30  2013-07    217            188
31  2013-08    196            179
32  2013-09    234            213
33  2013-10    207            188
34  2013-11    270            222
35  2013-12   4257            790
36  2014-01    243            210
37  2014-02    268            227
38  2014-03    305            255
39  2014-04    320            242
40  2014-05    279            230
41  2014-06    267            232
42  2014-07    248            212
43  2014-08    266            222
44  2014-09    276            230
45  2014-10    311            261
46  2014-11    297            237
47  2014-12   5451            794